# Generated by Django 4.2.4 on 2023-08-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
