# Generated by Django 4.2.4 on 2023-08-28 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_focus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focus',
            old_name='status',
            new_name='show',
        ),
    ]
