# Generated by Django 5.1.1 on 2024-10-03 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0006_group_show"),
    ]

    operations = [
        migrations.CreateModel(
            name="statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(max_length=20)),
                ("pm", models.FloatField(max_length=20)),
                ("rainfall", models.FloatField(max_length=20)),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
    ]
