# Generated by Django 5.1.1 on 2024-10-03 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0007_statistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
