# Generated by Django 5.1.1 on 2024-10-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0009_alter_statistics_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
