# Generated by Django 5.1.1 on 2024-10-03 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0010_alter_statistics_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="location_statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(max_length=255)),
                ("speedover", models.IntegerField(max_length=255)),
                ("average_speed", models.IntegerField(max_length=255)),
                (
                    "namelocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="module.location",
                    ),
                ),
            ],
        ),
    ]
